name: website
channels:
  - conda-forge
dependencies:
  - python=3.7.8
  - sphinx=3.1.2
  - pip
  - pip:
      - pydata-sphinx-theme==0.3.1
      - myst-parser==0.9.1
      # - myst-nb==0.8.4
      - ablog==0.10.6
      - nbsphinx
